spring:
  datasource:
    url:
    #    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=Asia/Shanghai
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.iwhalecloud.lottery.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
logging:
  level:
    root: info
    com.iwhalecloud.lottery.mapper: debug
