spring:
  datasource:
    url: jdbc:mysql://117.78.8.245:3306/lottery?serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=Asia/Shanghai
    username: lottery
    password: 1q2w3e4!QQQQQQQQQQ
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.iwhalecloud.lottery.entity
  mapper-locations: classpath:mapper/*.xml
  #≈‰÷√Õ’∑Âœ¬ªÆœﬂ
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
logging:
  level:
    root: info
    com.iwhalecloud.lottery.mapper: debug
