spring:
  datasource:
    url: 3mzyC9FZUn3DHwKnn/6UKBiB8EQPrlub8s8WAWpyiz8aikOQMAa/HwyKGWznjSVcr09aqfJpXIVgw8y8Q5E+Wnfgw9YTCevhqwh4CEj/e7Q=
    #    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=Asia/Shanghai
    username: YLkZw3UUudptdf5zRljWyA==
    password: HZWa1EoDKi332ykl7KzP0uPfglKgwPmi+TxW4FCwiFg=
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.iwhalecloud.lottery.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
logging:
  level:
    root: info
    com.iwhalecloud.lottery.mapper: debug
